namespace AgileConfig.BlazorUI.Localizations.Partial
{
    public class Pages
    {

        public class Rootobject
        {
            public string submit { get; set; }
            public string saving { get; set; }
            public string loading { get; set; }
            public string adding { get; set; }
            public string add_success { get; set; }
            public string add_fail { get; set; }
            public string save_success { get; set; }
            public string save_fail { get; set; }
            public string deleting { get; set; }
            public string delete_success { get; set; }
            public string delete_fail { get; set; }
            public string refreshing { get; set; }
            public string refresh_success { get; set; }
            public string refresh_fail { get; set; }
            public string enabled0 { get; set; }
            public string enabled1 { get; set; }
            public string success { get; set; }
            public string failed { get; set; }
            public string disconnecting { get; set; }
            public string disconnect_success { get; set; }
            public string disconnect_fail { get; set; }
            public string publishing { get; set; }
            public string publish_success { get; set; }
            public string publish_fail { get; set; }
            public string offlining { get; set; }
            public string offline_success { get; set; }
            public string offline_fail { get; set; }
            public string rollbacking { get; set; }
            public string rollback_success { get; set; }
            public string rollback_fail { get; set; }
            public string resetpasswordtitle { get; set; }
            public string resetpasswordoldpassword { get; set; }
            public string resetpasswordnewpassword { get; set; }
            public string resetpasswordnewpassword_ag { get; set; }
            public string resetpasswordupdate_success { get; set; }
            public string resetpasswordupdate_fail { get; set; }
            public string pageslayoutsuserLayouttitle { get; set; }
            public string pagesloginaccountLogintab { get; set; }
            public string pagesloginaccountLoginerrorMessage { get; set; }
            public string pagesloginusernameplaceholder { get; set; }
            public string pagesloginusernamerequired { get; set; }
            public string pagesloginpasswordplaceholder { get; set; }
            public string pagesloginpasswordrequired { get; set; }
            public string pagesloginphoneLogintab { get; set; }
            public string pagesloginphoneLoginerrorMessage { get; set; }
            public string pagesloginphoneNumberplaceholder { get; set; }
            public string pagesloginphoneNumberrequired { get; set; }
            public string pagesloginphoneNumberinvalid { get; set; }
            public string pageslogincaptchaplaceholder { get; set; }
            public string pageslogincaptcharequired { get; set; }
            public string pagesloginphoneLogingetVerificationCode { get; set; }
            public string pagesgetCaptchaSecondText { get; set; }
            public string pagesloginrememberMe { get; set; }
            public string pagesloginforgotPassword { get; set; }
            public string pagesloginsubmit { get; set; }
            public string pagesloginloginWith { get; set; }
            public string pagesloginregisterAccount { get; set; }
            public string pagesloginloginfail { get; set; }
            public string pagesloginloginsuccess { get; set; }
            public string pageswelcomeadvancedComponent { get; set; }
            public string pageswelcomelink { get; set; }
            public string pageswelcomeadvancedLayout { get; set; }
            public string pageswelcomealertMessage { get; set; }
            public string pagesadminsubPagetitle { get; set; }
            public string pagesadminsubPagealertMessage { get; set; }
            public string pagesinitpasswordtab { get; set; }
            public string pagesinitpasswordsubmit { get; set; }
            public string pagesinitpasswordag_passwordplaceholder { get; set; }
            public string pagesinitpasswordinit_tip { get; set; }
            public string pagesinitpasswordinit_success { get; set; }
            public string pageshomesummarynode { get; set; }
            public string pageshomesummaryapp { get; set; }
            public string pageshomesummaryconfig { get; set; }
            public string pageshomesummaryclient { get; set; }
            public string pageshomesummaryservice { get; set; }
            public string pagesnodeactionadd { get; set; }
            public string pagesnodeactiondelete { get; set; }
            public string pagesnodeactionrefresh { get; set; }
            public string pagesnodetablecolsaddress { get; set; }
            public string pagesnodetablecolsremark { get; set; }
            public string pagesnodetablecolslastEcho { get; set; }
            public string pagesnodetablecolsstatus { get; set; }
            public string pagesnodetablecolsstatus1 { get; set; }
            public string pagesnodetablecolsstatus0 { get; set; }
            public string pagesnodetablecolsaction { get; set; }
            public string pagesnodefromtips { get; set; }
            public string pagesnodeactiondeletetips { get; set; }
            public string pagesnodedelete_msg { get; set; }
            public string pagesapptablecolsappname { get; set; }
            public string pagesapptablecolsappid { get; set; }
            public string pagesapptablecolssecret { get; set; }
            public string pagesapptablecolscreate_time { get; set; }
            public string pagesapptablecolsupdate_time { get; set; }
            public string pagesapptablecolspublic { get; set; }
            public string pagesapptablecolslink { get; set; }
            public string pagesapptablecolsenabled { get; set; }
            public string pagesapptablecolsaction { get; set; }
            public string pagesapptablecolsactionconfigs { get; set; }
            public string pagesapptablecolsactionedit { get; set; }
            public string pagesapptablecolsactiondelete { get; set; }
            public string pagesapptablecolsactionadd { get; set; }
            public string pagesappformtitleadd { get; set; }
            public string pagesappformtitleedit { get; set; }
            public string pagesappformname { get; set; }
            public string pagesappformid { get; set; }
            public string pagesappformsecret { get; set; }
            public string pagesappformpublic { get; set; }
            public string pagesappformpublictooltip { get; set; }
            public string pagesappformconnected { get; set; }
            public string pagesappformconnectedtooltip { get; set; }
            public string pagesappformenabled { get; set; }
            public string pagesappdelete_msg { get; set; }
            public string pagesappinheritancedtrue { get; set; }
            public string pagesappinheritancedfalse { get; set; }
            public string pagesclienttablecolsid { get; set; }
            public string pagesclienttablecolsnode { get; set; }
            public string pagesclienttablecolsappid { get; set; }
            public string pagesclienttablecolsname { get; set; }
            public string pagesclienttablecolstag { get; set; }
            public string pagesclienttablecolsip { get; set; }
            public string pagesclienttablecolsappname { get; set; }
            public string pagesclienttablecolsaction { get; set; }
            public string pagesclienttablecolsactionrefresh { get; set; }
            public string pagesclienttablecolsactiondisconnect { get; set; }
            public string pagesclientheadertitle { get; set; }
            public string pagesclientdisconnect_message { get; set; }
            public string pageslogstableappname { get; set; }
            public string pageslogstabletype { get; set; }
            public string pageslogstabletype0 { get; set; }
            public string pageslogstabletype1 { get; set; }
            public string pageslogstabletime { get; set; }
            public string pageslogstablecontent { get; set; }
            public string pagesconfigsbreadcrumbName { get; set; }
            public string pagesconfigstablecolsg { get; set; }
            public string pagesconfigstablecolsk { get; set; }
            public string pagesconfigstablecolsv { get; set; }
            public string pagesconfigstablecolsdesc { get; set; }
            public string pagesconfigstablecolscreate_time { get; set; }
            public string pagesconfigstablecolsstatus { get; set; }
            public string pagesconfigstablecolsstatus0 { get; set; }
            public string pagesconfigstablecolsstatus1 { get; set; }
            public string pagesconfigstablecolsaction { get; set; }
            public string pagesconfigstablecolsactionadd { get; set; }
            public string pagesconfigstablecolsactionimportfromjosnfile { get; set; }
            public string pagesconfigstablecolsactionpopimportfromjosnfile { get; set; }
            public string pagesconfigstablecolsactionexportJson { get; set; }
            public string pagesconfigstablecolsactionedit { get; set; }
            public string pagesconfigstablecolsactiondelete { get; set; }
            public string pagesconfigstablecolsactionpublish { get; set; }
            public string pagesconfigstablecolsactionoffline { get; set; }
            public string pagesconfigstablecolsactionhistory { get; set; }
            public string pagesconfigsfromaddtitle { get; set; }
            public string pagesconfigsfromaddapp { get; set; }
            public string pagesconfigsfromimportjsonselectfile { get; set; }
            public string pagesconfigstablecolsvtip { get; set; }
            public string pagesconfighistorytitle { get; set; }
            public string pagesconfighistoryrollback { get; set; }
            public string pagesconfighistorycurrent { get; set; }
            public string pagesconfigconfirm_rollback { get; set; }
            public string pagesconfigconfirm_delete { get; set; }
            public string pagesconfigconfirm_publish { get; set; }
            public string pagesconfigconfirm_offline { get; set; }
            public string pagesconfigconfirm_publish_some { get; set; }
            public string pagesconfigconfirm_offline_some { get; set; }
            public string pagesconfigwaitpublish_at_least_one { get; set; }
            public string pagesconfigonline_at_least_one { get; set; }
        }

    }
}
